USE CSE_3A_156;

CREATE TABLE SALES_DATA
(
	REGION VARCHAR(50),
	PRODUCT VARCHAR(20),
	SALES_AMOUNT DECIMAL(6,2),
	YEAR INT
)

INSERT INTO SALES_DATA 
VALUES 
	('NORTH AMERICA','WATCH',1500,2023),
	('EOUROPE','MOBILE',1200,2023),
	('ASIA','WATCH',1800,2023),
	('NORTH AMERICA','TV',900,2024),
	('EOUROPE','WATCH',2000,2024),
	('ASIA','MOBILE',1000,2024),
	('NORTH AMERICA','MOBILE',1600,2023),
	('EOUROPE','TV',1500,2023),
	('ASIA','TV',1100,2024),
	('NORTH AMERICA','WATCH',1700,2024)

SELECT * FROM SALES_DATA;

--Perform SQL queries for Group by with having and Order by

--Part – A:

--1. Display Total Sales Amount by REGION.
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA
GROUP BY REGION;

--2. Display Average Sales Amount by PRODUCT
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG_SALES FROM SALES_DATA 
GROUP BY PRODUCT;

--3. Display Maximum Sales Amount by Year
SELECT YEAR,MAX(SALES_AMOUNT) AS MAX_SALES FROM SALES_DATA 
GROUP BY YEAR;

--4. Display Minimum Sales Amount by REGION and Year
SELECT  REGION,YEAR,MIN(SALES_AMOUNT) AS MIN_SALES FROM SALES_DATA 
GROUP BY REGION,YEAR;

--5. Count of PRODUCTs Sold by REGION
SELECT REGION,COUNT(PRODUCT) AS PRODUCT FROM SALES_DATA
GROUP BY REGION;

--6. Display Sales Amount by Year and PRODUCT
SELECT YEAR,PRODUCT,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA 
GROUP BY YEAR,PRODUCT;

--7. Display REGIONs with Total Sales Greater Than 5000
SELECT REGION,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA 
GROUP BY REGION 
HAVING SUM(SALES_AMOUNT)>5000;

--8. Display PRODUCTs with Average Sales Less Than 10000
SELECT PRODUCT,AVG(SALES_AMOUNT) AS PRODUCT FROM SALES_DATA 
GROUP BY PRODUCT 
HAVING AVG(SALES_AMOUNT)<10000;

--9. Display Years with Maximum Sales Exceeding 500
SELECT YEAR,MAX(SALES_AMOUNT) AS SALES FROM SALES_DATA 
GROUP BY YEAR 
HAVING MAX(SALES_AMOUNT)>500;

--10. Display REGIONs with at Least 3 Distinct PRODUCTs Sold.
SELECT * FROM SALES_DATA;
SELECT REGION,COUNT(DISTINCT PRODUCT) AS PRODUCT FROM SALES_DATA 
GROUP BY REGION 
HAVING COUNT(DISTINCT PRODUCT)>=3;

--11. Display Years with Minimum Sales Less Than 1000
SELECT YEAR,MIN(SALES_AMOUNT) AS SALES FROM SALES_DATA 
GROUP BY YEAR 
HAVING MIN(SALES_AMOUNT)<1000;

--12.Display Total Sales Amount by REGION for Year 2023, Sorted by Total Amount
SELECT REGION,YEAR,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA GROUP BY REGION,Year HAVING Year=2023;

--13.Find the REGION Where 'Mobile' Had the Lowest Total Sales Across All Years.
SELECT TOP 1 REGION,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA GROUP BY REGION ORDER BY SALES;

--14.Find the PRODUCT with the Highest Sales Across All REGIONs in 2023.
SELECT TOP 1 PRODUCT,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA GROUP BY PRODUCT ORDER BY SALES DESC;

--15.Find REGIONs Where 'TV' Sales in 2023 Were Greater Than 1000.
SELECT TOP 1 PRODUCT,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA WHERE YEAR=2023 
GROUP BY PRODUCT HAVING PRODUCT = 'TV' AND SUM(SALES_AMOUNT)>1000;


--Part � B:

--1.Display Count of Orders by Year and REGION, Sorted by Year and REGION
SELECT YEAR,REGION, COUNT(*) AS Y FROM SALES_DATA GROUP BY YEAR,REGION ORDER BY YEAR,REGION;

--2.Display REGIONs with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by REGION
SELECT REGION, MAX(SALES_AMOUNT) AS AMOUNT FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT)>1000 ORDER BY REGION;

--3.Display Years with Total Sales Amount Less Than 10000, Sorted by Year Descending
SELECT YEAR,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT)<10000 ORDER BY YEAR DESC;

--4.Display Top 3 REGIONs by Total Sales Amount in Year 2024
SELECT TOP 3 REGION ,SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA WHERE YEAR = 2024 GROUP BY REGION ;

--5.Find the Year with the Lowest Total Sales Across All REGIONs.
SELECT TOP 1 YEAR , SUM(SALES_AMOUNT) AS SALES FROM SALES_DATA GROUP BY YEAR ORDER BY SALES;

--Part-C:

--1.Display PRODUCTs with Average Sales Amount Between 1000 and 2000, Ordered by PRODUCT Name
SELECT PRODUCT ,AVG(SALES_AMOUNT) AS PROD_NAME FROM SALES_DATA GROUP BY PRODUCT 
HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000 ORDER BY PROD_NAME;

--2.Display Years with More Than 1 Orders from Each REGION
SELECT YEAR,REGION , COUNT(PRODUCT) AS SALES FROM SALES_DATA GROUP BY YEAR,REGION HAVING COUNT(PRODUCT)>1;

--3.Display REGIONs with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending.
SELECT REGION,AVG(SALES_AMOUNT) AS SALES FROM SALES_DATA WHERE YEAR = 2023
GROUP BY REGION HAVING AVG(SALES_AMOUNT)>1500 ORDER BY SALES DESC;

--4.Find out REGION wise duplicate PRODUCT.
SELECT REGION,PRODUCT AS PRO FROM SALES_DATA GROUP BY REGION,PRODUCT
HAVING COUNT(*) > 1

--5.Find out year wise duplicate PRODUCT.
SELECT YEAR,PRODUCT AS PRO FROM SALES_DATA GROUP BY YEAR,PRODUCT
HAVING COUNT(*) > 1